### ISSUE TITLE
Compile Failures from v1.9

### ISSUE THREAD

**Issue by theory** [ossc-db/pg_store_plans#46]
On Ubuntu Linux with PostgreSQL 15:

```
In file included from pg_store_plans.c:33:
pg_store_plans.c: In function 'pg_store_plans_internal':
pg_store_plans.c:1697:54: error: 'Counters' has no member named 'shared_blk_read_time'; did you mean 'shared_blks_read'?
 1697 |                 values[i++] = Float8GetDatumFast(tmp.shared_blk_read_time);
      |                                                      ^~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/15/server/postgres.h:802:46: note: in definition of macro 'Float8GetDatumFast'
  802 | #define Float8GetDatumFast(X) Float8GetDatum(X)
      |                                              ^
pg_store_plans.c:1698:54: error: 'Counters' has no member named 'shared_blk_write_time'; did you mean 'shared_blks_written'?
 1698 |                 values[i++] = Float8GetDatumFast(tmp.shared_blk_write_time);
      |                                                      ^~~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/15/server/postgres.h:802:46: note: in definition of macro 'Float8GetDatumFast'
  802 | #define Float8GetDatumFast(X) Float8GetDatum(X)
      |                                              ^
pg_store_plans.c:1702:62: error: 'Counters' has no member named 'local_blk_read_time'; did you mean 'temp_blk_read_time'?
 1702 |                         values[i++] = Float8GetDatumFast(tmp.local_blk_read_time);
      |                                                              ^~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/15/server/postgres.h:802:46: note: in definition of macro 'Float8GetDatumFast'
  802 | #define Float8GetDatumFast(X) Float8GetDatum(X)
      |                                              ^
pg_store_plans.c:1703:62: error: 'Counters' has no member named 'local_blk_write_time'; did you mean 'temp_blk_write_time'?
 1703 |                         values[i++] = Float8GetDatumFast(tmp.local_blk_write_time);
      |                                                              ^~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/15/server/postgres.h:802:46: note: in definition of macro 'Float8GetDatumFast'
  802 | #define Float8GetDatumFast(X) Float8GetDatum(X)
      |                                              ^
make: *** [<builtin>: pg_store_plans.o] Error 1
```

And with Postgres 16:

```
In file included from /usr/include/postgresql/16/server/postgres.h:45,
                 from pg_store_plans.c:33:
pg_store_plans.c: In function 'pg_store_plans_internal':
pg_store_plans.c:1697:54: error: 'Counters' has no member named 'shared_blk_read_time'; did you mean 'shared_blks_read'?
 1697 |                 values[i++] = Float8GetDatumFast(tmp.shared_blk_read_time);
      |                                                      ^~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/c.h:916:29: note: in definition of macro 'StaticAssertStmt'
  916 |         do { _Static_assert(condition, errmessage); } while(0)
      |                             ^~~~~~~~~
/usr/include/postgresql/16/server/c.h:962:10: note: in expansion of macro 'StaticAssertExpr'
  962 |         (StaticAssertExpr(__builtin_types_compatible_p(__typeof__(varname), typename), \
      |          ^~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/postgres.h:552:10: note: in expansion of macro 'AssertVariableIsOfTypeMacro'
  552 |         (AssertVariableIsOfTypeMacro(X, double), Float8GetDatum(X))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
pg_store_plans.c:1697:31: note: in expansion of macro 'Float8GetDatumFast'
 1697 |                 values[i++] = Float8GetDatumFast(tmp.shared_blk_read_time);
      |                               ^~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/c.h:962:27: error: expression in static assertion is not an integer
  962 |         (StaticAssertExpr(__builtin_types_compatible_p(__typeof__(varname), typename), \
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/c.h:916:29: note: in definition of macro 'StaticAssertStmt'
  916 |         do { _Static_assert(condition, errmessage); } while(0)
      |                             ^~~~~~~~~
/usr/include/postgresql/16/server/c.h:962:10: note: in expansion of macro 'StaticAssertExpr'
  962 |         (StaticAssertExpr(__builtin_types_compatible_p(__typeof__(varname), typename), \
      |          ^~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/postgres.h:552:10: note: in expansion of macro 'AssertVariableIsOfTypeMacro'
  552 |         (AssertVariableIsOfTypeMacro(X, double), Float8GetDatum(X))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
pg_store_plans.c:1697:31: note: in expansion of macro 'Float8GetDatumFast'
 1697 |                 values[i++] = Float8GetDatumFast(tmp.shared_blk_read_time);
      |                               ^~~~~~~~~~~~~~~~~~
In file included from pg_store_plans.c:33:
pg_store_plans.c:1697:54: error: 'Counters' has no member named 'shared_blk_read_time'; did you mean 'shared_blks_read'?
 1697 |                 values[i++] = Float8GetDatumFast(tmp.shared_blk_read_time);
      |                                                      ^~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/postgres.h:552:65: note: in definition of macro 'Float8GetDatumFast'
  552 |         (AssertVariableIsOfTypeMacro(X, double), Float8GetDatum(X))
      |                                                                 ^
In file included from /usr/include/postgresql/16/server/postgres.h:45,
                 from pg_store_plans.c:33:
pg_store_plans.c:1698:54: error: 'Counters' has no member named 'shared_blk_write_time'; did you mean 'shared_blks_written'?
 1698 |                 values[i++] = Float8GetDatumFast(tmp.shared_blk_write_time);
      |                                                      ^~~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/c.h:916:29: note: in definition of macro 'StaticAssertStmt'
  916 |         do { _Static_assert(condition, errmessage); } while(0)
  962 |         (StaticAssertExpr(__builtin_types_compatible_p(__typeof__(varname), typename), \
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/c.h:916:29: note: in definition of macro 'StaticAssertStmt'
  916 |         do { _Static_assert(condition, errmessage); } while(0)
      |                             ^~~~~~~~~
/usr/include/postgresql/16/server/c.h:962:10: note: in expansion of macro 'StaticAssertExpr'
  962 |         (StaticAssertExpr(__builtin_types_compatible_p(__typeof__(varname), typename), \
      |          ^~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/postgres.h:552:10: note: in expansion of macro 'AssertVariableIsOfTypeMacro'
  552 |         (AssertVariableIsOfTypeMacro(X, double), Float8GetDatum(X))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
pg_store_plans.c:1702:39: note: in expansion of macro 'Float8GetDatumFast'
 1702 |                         values[i++] = Float8GetDatumFast(tmp.local_blk_read_time);
      |                                       ^~~~~~~~~~~~~~~~~~
In file included from pg_store_plans.c:33:
pg_store_plans.c:1702:62: error: 'Counters' has no member named 'local_blk_read_time'; did you mean 'temp_blk_read_time'?
 1702 |                         values[i++] = Float8GetDatumFast(tmp.local_blk_read_time);
      |                                                              ^~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/postgres.h:552:65: note: in definition of macro 'Float8GetDatumFast'
  552 |         (AssertVariableIsOfTypeMacro(X, double), Float8GetDatum(X))
      |                                                                 ^
In file included from /usr/include/postgresql/16/server/postgres.h:45,
                 from pg_store_plans.c:33:
pg_store_plans.c:1703:62: error: 'Counters' has no member named 'local_blk_write_time'; did you mean 'temp_blk_write_time'?
 1703 |                         values[i++] = Float8GetDatumFast(tmp.local_blk_write_time);
      |                                                              ^~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/c.h:916:29: note: in definition of macro 'StaticAssertStmt'
  916 |         do { _Static_assert(condition, errmessage); } while(0)
      |                             ^~~~~~~~~
/usr/include/postgresql/16/server/c.h:962:10: note: in expansion of macro 'StaticAssertExpr'
  962 |         (StaticAssertExpr(__builtin_types_compatible_p(__typeof__(varname), typename), \
      |          ^~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/postgres.h:552:10: note: in expansion of macro 'AssertVariableIsOfTypeMacro'
  552 |         (AssertVariableIsOfTypeMacro(X, double), Float8GetDatum(X))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
pg_store_plans.c:1703:39: note: in expansion of macro 'Float8GetDatumFast'
 1703 |                         values[i++] = Float8GetDatumFast(tmp.local_blk_write_time);
      |                                       ^~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/c.h:962:27: error: expression in static assertion is not an integer
  962 |         (StaticAssertExpr(__builtin_types_compatible_p(__typeof__(varname), typename), \
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/c.h:916:29: note: in definition of macro 'StaticAssertStmt'
  916 |         do { _Static_assert(condition, errmessage); } while(0)
      |                             ^~~~~~~~~
/usr/include/postgresql/16/server/c.h:962:10: note: in expansion of macro 'StaticAssertExpr'
  962 |         (StaticAssertExpr(__builtin_types_compatible_p(__typeof__(varname), typename), \
      |          ^~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/postgres.h:552:10: note: in expansion of macro 'AssertVariableIsOfTypeMacro'
  552 |         (AssertVariableIsOfTypeMacro(X, double), Float8GetDatum(X))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
pg_store_plans.c:1703:39: note: in expansion of macro 'Float8GetDatumFast'
 1703 |                         values[i++] = Float8GetDatumFast(tmp.local_blk_write_time);
      |                                       ^~~~~~~~~~~~~~~~~~
In file included from pg_store_plans.c:33:
pg_store_plans.c:1703:62: error: 'Counters' has no member named 'local_blk_write_time'; did you mean 'temp_blk_write_time'?
 1703 |                         values[i++] = Float8GetDatumFast(tmp.local_blk_write_time);
      |                                                              ^~~~~~~~~~~~~~~~~~~~
/usr/include/postgresql/16/server/postgres.h:552:65: note: in definition of macro 'Float8GetDatumFast'
  552 |         (AssertVariableIsOfTypeMacro(X, double), Float8GetDatum(X))
      |                                                                 ^
make: *** [<builtin>: pg_store_plans.o] Error 1
```

**Comment by devrimgunduz** [comment]
@theory they released a version which works only against PostgreSQL 17. *sigh*.

**Comment by theory** [comment]
Likely broken by 39cc243.
